version: '3.8'

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-docker-certs:
  jenkins-data:

services:
  docker:
    image: docker:dind
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 2376:2376
    command: --storage-driver overlay2

  jenkins:
    image: myjenkins-blueocean:jdk17
    restart: on-failure
    networks:
      jenkins:
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: '1'
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - $HOME/jenkins:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
