
pipeline { 
    agent any
    
    stages { 
        stage('Checkout') {
            steps {
                echo 'Checking out...'
                git branch: 'main', credentialsId: 'FranciscaNogueira-github-credentials' , url:
                'https://github.com/FranciscaNogueira/devops-23-24-JPE-PSM-1231829.git'
            }
        } 
        stage('Build') {
            steps {
                dir('CA5/CA2Part2') {
                    echo 'Building...'
                    sh './gradlew clean build'
                }
            } 
        }
        stage('Test') {
            steps {
                dir('CA5/CA2Part2') {
                    echo 'Testing...'
                    sh './gradlew test'
                    junit 'build/test-results/test/*.xml'
                }
            } 
        }
        stage('Javadoc') {
            steps {
                dir('CA5/CA2Part2') {
                    echo 'Generating Javadoc...'
                    sh './gradlew javadoc'
                }
            }
        }
        stage('Archiving') { 
            steps {
                dir('CA5/CA2Part2') {
                    echo 'Archiving...'
                    archiveArtifacts 'build/distributions/*' 
                }
            }
        }
        stage ('Docker Image') {
            steps {
                script {
                    docker.build("my-image:${env.BUILD_ID}")
                }
            }
        }
    }
}